all:
	#g++ Principal.cpp -std=c++17 -I/home/isma/DopenCV/librerias/include/opencv4 \
	#	-L/home/isma/DopenCV/librerias/lib \
	#	-lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc \
	#	-lopencv_video -lopencv_videoio -lopencv_features2d -lopencv_objdetect \
	#	-lopencv_ml \
	#	-o vision.bin
	g++ validacion.cpp -std=c++17 -I/home/isma/DopenCV/librerias/include/opencv4 \
    -L/home/isma/DopenCV/librerias/lib -lopencv_core -lopencv_imgcodecs -lopencv_highgui \
    -lopencv_imgproc -lopencv_ml -lopencv_video -lopencv_videoio -o validacion

run:
	./validacion
